version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:14.13.1
    steps:
      - checkout
      - run:
          command: npm install
      - run:
          command: npm run build
  test:
    docker:
      - image: cimg/node:14.13.1
    steps:
      - checkout
      - run:
          command: npm run test
orbs:
  orb: choilmto/orb@1.0.1
workflows:
  build-log:
    jobs:
      - orb/workflow-collector:
          org-name: "choilmto"
      - build
      - test
