jobs:
  build:
    docker:
      - image: cimg/node:14.13.1
    steps:
      - checkout
      - run:
          command: npm install
      - run:
          command: npm run build
  
orbs:
  orb: choilmto/orb@0.1.0
version: 2.1
workflows:
  build:
    jobs:
      - orb/workflow-collector
      - build
