version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:14.13.1
    steps:
      - checkout
      - run:
          command: npm install
      - run:
          command: npm run build
orbs:
  orb: choilmto/orb@0.4.0
workflows:
  build-log:
    jobs:
      - orb/workflow-collector:
          org-name: "choilmto"
          vcs-slug: "gh"
      - build
